from pydantic import BaseModel, Field
from typing import Optional, Dict, Any

class QueryRequest(BaseModel):
    query: str = Field(..., description="The input query string.")
    top_k: Optional[int] = Field(5, description="Number of top similar chunks to retrieve")
    
class QueryResponse(BaseModel):
    response: str = Field(..., description="The response generated by the LLM.")
    retrieved_chunks: list = Field(..., description="List of retrieved chunks relevant to the query.")